version: '1'

services:

  mysql-development:
    image: mysql:latest
    container_name: urnshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: urnshop
    ports:
      - "3306:3306"

  admin:
    container_name: urnshop-adminer
    image: adminer
    ports:
      - "8080:8080"